Repository Shtian/vscode-svgocd, pull requests merged in 2019-08, with the labels that each got.

#7 Feat/parse svgo yaml
  README.md
  package-lock.json
  package.json
  src/configuration.ts
  src/extension.ts
  src/optimizeSVG.ts
Labels: enhancement

#16 Fix/use eslint prettier
  .eslintrc.js
  .prettierrc.js
  .vscodeignore
  README.md
  azure-pipelines.yml
  package-lock.json
  package.json
  src/configuration.ts
  src/extension.ts
  src/optimizeSVG.ts
  src/test/runTest.ts
  src/test/suite/extension.test.ts
  src/test/suite/index.ts
  src/utils.ts
  tslint.json
Labels: enhancement

#19 Fix/rename main class
  README.md
  images/howto.gif
  src/extension.ts
  src/optimizeSVG.ts
Labels: 📝 documentation

#21 Add optimized percentage
  src/optimizeSVG.ts
  src/utils.ts
Labels: ✨ enhancement

#23 fix: read conf on workspace change
  src/extension.ts
Labels: 🐛 bug
